# Generated by Django 3.2.8 on 2021-10-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=0, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sneaker',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sneaker',
            name='slug',
            field=models.SlugField(default=0, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sneaker',
            name='stock',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
